dcSpark/shinkai-local-ai-agents

.github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, README.md, package-lock.json, package.json
- Update ollama to v0.1.43
- Update shinkai-node to v0.7.12
- Improve readme
=> - improve: ollama v0.7.43 - shinkai-node v0.7.12

.github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, README.md, package-lock.json, package.json
Update:
- Shinkai Node v0.7.13
- Ollama v0.1.44
- Bump 0.7.19
=> - improve: shinkai-node v0.7.13 - ollama v0.1.44

.github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, README.md
Upgrade
- ollama: v0.2.1
- shinkai-node: v0.7.17
=> - improve: ollama 0.2.1 and shinkai-node 0.7.17

apps/shinkai-desktop/src/components/subscriptions/subscriptions.tsx, apps/shinkai-desktop/src/components/vector-fs/components/all-files-tab.tsx, apps/shinkai-desktop/src/components/vector-fs/components/vector-fs-item.tsx, apps/shinkai-desktop/src/components/vector-fs/components/vector-fs-toggle-sort-name.tsx, libs/shinkai-ui/src/assets/icons/general.tsx, libs/shinkai-ui/src/components/toggle.tsx
feat: sorting vector fs by its name
fix: subscription feed UI
fix: create AI chat from vector fs
=> Fix: subscription feed UI, misc fixes on vector FS 

apps/shinkai-desktop/src/components/vector-fs/components/vector-fs-item-detail.tsx, apps/shinkai-desktop/src/pages/galxe-subscriptions.tsx, apps/shinkai-visor/src/components/node-files/vector-fs-item-detail.tsx, libs/shinkai-i18n/locales/en-US.json, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-i18n/locales/id-ID.json, libs/shinkai-i18n/locales/ja-JP.json, libs/shinkai-i18n/locales/zh-CN.json, libs/shinkai-i18n/src/lib/default/index.ts
- fix: coming soon label
- fix: overflow text in vector fs names
- fix: galxe quests labels
=> - improve: UI improvements

apps/shinkai-desktop/src-tauri/Cargo.lock, apps/shinkai-desktop/src-tauri/Cargo.toml, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/logger.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/ollama_process_handler.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/shinkai_node_process_handler.rs, apps/shinkai-desktop/src/lib/shinkai-node-manager/shinkai-node-manager-client-types.ts, apps/shinkai-desktop/src/store/shinkai-node-manager.ts, apps/shinkai-desktop/src/windows/shinkai-node-manager/main.tsx
- fix: scape control characters from string in logs
- fix: api port label
- fix: ollama and shinkai-node health proof
- fix: isInUse state when auth change and node is not running
=> - fix: several fixes in shinkai node manager

apps/shinkai-desktop/src-tauri/src/local_shinkai_node/shinkai_node_manager.rs, apps/shinkai-desktop/src/windows/shinkai-node-manager/main.tsx
- fix: download initial embedding model
- fix: wrong param on remove storage
=> - fix: fixes after qa

apps/shinkai-desktop/src/components/vector-fs/components/vector-fs-folder.tsx, apps/shinkai-desktop/src/pages/chat/chat-conversation.tsx, apps/shinkai-desktop/src/pages/chat/layout.tsx, apps/shinkai-visor/src/components/inbox/inbox.tsx, apps/shinkai-visor/src/components/node-files/vector-fs-folder.tsx, libs/shinkai-node-state/src/lib/mutations/exportConnection/index.ts, libs/shinkai-node-state/src/lib/mutations/exportConnection/types.ts, libs/shinkai-node-state/src/lib/mutations/exportConnection/useExportConnection.ts, libs/shinkai-node-state/src/lib/queries/scanOllamaModels/useScanOllamaModels.ts, libs/shinkai-ui/src/components/chat/message-list.tsx, libs/shinkai-ui/src/components/chat/message.tsx, package-lock.json, package.json
- fix: conversation layout when tables are big
- bump typescript 5.5.4
- fix: add workflow name when retrying or editing previous messages
- fix: duplication ollama models
=> Misc fixes

.github/workflows/audit.yml, .github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, libs/shinkai-message-ts/src/utils/wasm_helpers.test.ts, libs/shinkai-message-ts/src/wasm/ShinkaiMessageBuilderWrapper.test.ts, package-lock.json, package.json
- npm audit for prod dependencies
- CI uses .nvmrc node version
=> - fix: npm audit

apps/shinkai-desktop/src-tauri/capabilities/migrated.json, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/ollama_process_handler.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/process_utils.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/shinkai_node_process_handler.rs
- Properly kill sidecars by pid
- Enable windows drag permission
=> - fix: macos issues after refactor

apps/shinkai-desktop/src-tauri/Cargo.lock, apps/shinkai-desktop/src-tauri/Cargo.toml, apps/shinkai-desktop/src-tauri/src/main.rs, apps/shinkai-desktop/src-tauri/src/tray.rs, apps/shinkai-desktop/src-tauri/tauri.conf.json, apps/shinkai-desktop/src-tauri/tauri.macos.conf.json
=> - fix: system tray issues

apps/shinkai-desktop/src/components/chat/constants.ts, apps/shinkai-desktop/src/pages/create-agent.tsx, apps/shinkai-visor/src/components/agents/add-agent.tsx, libs/shinkai-i18n/src/lib/default/index.ts, libs/shinkai-message-ts/src/api/jobs/index.ts, libs/shinkai-message-ts/src/api/jobs/types.ts, libs/shinkai-message-ts/src/models/SchemaTypes.ts, libs/shinkai-message-ts/src/wasm/SerializedLLMProviderWrapper.ts, libs/shinkai-node-state/src/lib/utils/models.ts
=> support custom model ids

apps/shinkai-desktop/src/components/reset-storage-before-connect-confirmation-prompt.tsx, apps/shinkai-desktop/src/pages/get-started.tsx, libs/shinkai-ui/src/components/button.tsx
=> - fix: added disable and isLoading props to start node buttons

README.md, apps/shinkai-desktop/src-tauri/Cargo.lock, apps/shinkai-desktop/src-tauri/Cargo.toml, apps/shinkai-desktop/src/App.tsx, apps/shinkai-desktop/src/components/sheet/utils/use-table-hotkeys.ts, apps/shinkai-desktop/src/lib/shinkai-node-manager/ollama-client.ts, apps/shinkai-desktop/src/lib/shinkai-node-manager/shinkai-node-manager-hooks.ts, apps/shinkai-desktop/src/lib/updater/updater-client.ts, apps/shinkai-desktop/src/store/shinkai-node-manager.ts, apps/shinkai-desktop/src/store/sync-utils.ts, apps/shinkai-desktop/src/windows/shinkai-node-manager/main.tsx, apps/shinkai-desktop/src/windows/spotlight/main.tsx, package-lock.json, package.json
=> - fix: sync storage infinite rehyrate loop

apps/shinkai-desktop/src/components/chat/chat-action-bar/chat-config-action-bar.tsx, apps/shinkai-desktop/src/components/chat/conversation-footer.tsx, apps/shinkai-desktop/src/components/chat/message-extra.tsx, apps/shinkai-desktop/src/components/chat/message-stream.tsx, apps/shinkai-desktop/src/components/sheet/data-table-actions.tsx, apps/shinkai-desktop/src/pages/chat/chat-conversation.tsx, apps/shinkai-desktop/src/pages/chat/empty-message.tsx, apps/shinkai-desktop/src/pages/chat/layout.tsx, apps/shinkai-desktop/src/pages/get-started.tsx, apps/shinkai-desktop/src/pages/sheet-dashboard.tsx, libs/shinkai-message-ts/src/api/general/types.ts, libs/shinkai-message-ts/src/api/jobs/types.ts, libs/shinkai-node-state/src/v2/queries/getChatConversation/index.ts, libs/shinkai-node-state/src/v2/queries/getChatConversation/types.ts, libs/shinkai-ui/src/components/alert.tsx, libs/shinkai-ui/src/components/chat/chat-input.tsx, libs/shinkai-ui/src/components/chat/message.tsx
- feat: tool UI integration
- fix: set empty state when create new chat
- fix: overlap in shinkai project with selection toolbar
- fix: import sheet allows upload only csv and xlsx
- fix: expand input box
=> feat: tool calls UI + fixes

apps/shinkai-desktop/src-tauri/src/commands/spotlight_commands.rs, apps/shinkai-desktop/src-tauri/src/main.rs, apps/shinkai-desktop/src-tauri/src/windows/mod.rs, apps/shinkai-desktop/src/components/chat/chat-action-bar/ai-update-selection-action-bar.tsx, apps/shinkai-desktop/src/components/chat/conversation-footer.tsx, apps/shinkai-desktop/src/components/sheet/data-table-actions.tsx, apps/shinkai-desktop/src/components/sheet/table-chat.tsx, apps/shinkai-desktop/src/hooks/use-current-inbox.ts, apps/shinkai-desktop/src/pages/chat/empty-message.tsx, libs/shinkai-i18n/locales/en-US.json, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-i18n/locales/id-ID.json, libs/shinkai-i18n/locales/ja-JP.json, libs/shinkai-i18n/locales/zh-CN.json
- feat: add prompt suggestions
- feat: add AI selection in shinkai sheet chat
- feat: multiple upload files support 
- fix: shinkai sheet formula prompt
- fix: i18n
- fix: regex for reactjs artifacts code
=> feat: misc improvements

.github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, README.md, apps/shinkai-desktop/src-tauri/src/commands/shinkai_node_manager_commands.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/ollama_process_handler.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/shinkai_node_manager.rs, apps/shinkai-desktop/src-tauri/src/main.rs, apps/shinkai-desktop/src/lib/shinkai-node-manager/shinkai-node-manager-client.ts, apps/shinkai-desktop/src/pages/settings.tsx, libs/shinkai-i18n/locales/en-US.json, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-i18n/locales/id-ID.json, libs/shinkai-i18n/locales/ja-JP.json, libs/shinkai-i18n/locales/zh-CN.json, libs/shinkai-i18n/src/lib/default/index.ts
- bump Ollama to v0.4.0
- add ollama version to settings
=> - improve: bump ollama to 0.4.0

.github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, README.md, apps/shinkai-desktop/src-tauri/src/commands/shinkai_node_manager_commands.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/ollama_process_handler.rs, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/shinkai_node_manager.rs, apps/shinkai-desktop/src-tauri/src/main.rs, apps/shinkai-desktop/src/lib/shinkai-node-manager/shinkai-node-manager-client.ts, apps/shinkai-desktop/src/pages/settings.tsx, libs/shinkai-i18n/.i18nrc.js, libs/shinkai-i18n/locales/en-US.json, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-i18n/locales/id-ID.json, libs/shinkai-i18n/locales/ja-JP.json, libs/shinkai-i18n/locales/tr-TR.json, libs/shinkai-i18n/locales/zh-CN.json, libs/shinkai-i18n/scripts/translations.ts, libs/shinkai-i18n/src/lib/constants.ts, libs/shinkai-i18n/src/lib/default/index.ts
=> - feature: add tr-TR lang

apps/shinkai-desktop/src/components/playground-tool/components/tool-playground.tsx, apps/shinkai-desktop/src/components/playground-tool/hooks/use-tool-code.ts, libs/shinkai-message-ts/src/api/tools/index.ts, libs/shinkai-node-state/src/v2/mutations/executeToolCode/index.ts, libs/shinkai-node-state/src/v2/mutations/executeToolCode/types.ts, libs/shinkai-node-state/src/v2/mutations/saveToolCode/index.ts, libs/shinkai-node-state/src/v2/mutations/saveToolCode/types.ts
When opening a new playground a unique app-id and task-id is created
=> set x-shinkai-*

apps/shinkai-desktop/src-tauri/capabilities/main.json, apps/shinkai-desktop/src-tauri/capabilities/shinkai-node-manager.json, apps/shinkai-desktop/src-tauri/src/commands/logs.rs, apps/shinkai-desktop/src-tauri/src/commands/mod.rs, apps/shinkai-desktop/src-tauri/src/main.rs, apps/shinkai-desktop/src/lib/shinkai-logs/logs-client.ts, apps/shinkai-desktop/src/windows/shinkai-node-manager/main.tsx
Added command to retrieve the content of the log file managed by the tauri logging.
=> feat: retrieve logs

apps/shinkai-desktop/src/pages/layout/main-layout.tsx, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-message-ts/src/utils/inbox_name_handler.ts
- i18n ES for resetNodeWarning
- Help button send to the docs
- added .base-sep to the node name validation
=> fix: bug fixes testnet 3

apps/shinkai-desktop/src/components/playground-tool/components/tool-playground.tsx
- added close button
- fix text overflow (added a ellipsis)
- fix content overflow that was displaying some wrong scrolls
- added a tooltip to display the full name (when ellipsis you can't see the full name)
=> fix: ui tool playground knowledge

apps/shinkai-desktop/src-tauri/Cargo.lock, apps/shinkai-desktop/src-tauri/Cargo.toml, apps/shinkai-desktop/src-tauri/capabilities/shinkai-node-manager.json, apps/shinkai-desktop/src-tauri/src/main.rs, apps/shinkai-desktop/src/windows/shinkai-node-manager/main.tsx, package-lock.json, package.json
- add virtual scroller to improve logs render performance
- add refresh logs to display latests logs from the hdd
- improve open logs button. Now it really open the logs file with the default
- added disable/loading state to refresh and download logs buttons
=> feat: improvements app logs

apps/shinkai-desktop/src/components/shinkai-node-manager/components/ollama-model-install-button.tsx, apps/shinkai-desktop/src/pages/ais.tsx, package-lock.json
- Add removal of LLM provider when deleting an Ollama model
- Fetch and remove corresponding LLM provider for Ollama models
- Enhance error handling and logging for model removal
=> feat: improve Ollama model removal process

.github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, README.md, package-lock.json, package.json
- Update package version in package.json and package-lock.json to 0.9.16
- Update OLLAMA_VERSION to v0.6.0 and SHINKAI_NODE_VERSION to v0.9.13 in README.md and CI workflows
=> chore: Bump version to 0.9.16 and update dependencies

apps/shinkai-desktop/src-tauri/Cargo.lock, apps/shinkai-desktop/src-tauri/Cargo.toml, apps/shinkai-desktop/src-tauri/src/main.rs
- Integrated fix-path-env in the main function to ensure proper path handling.
=> Add fix-path-env dependency and integrate it in main function

apps/shinkai-desktop/src-tauri/Cargo.lock, apps/shinkai-desktop/src-tauri/Cargo.toml, apps/shinkai-desktop/src-tauri/capabilities/main.json, apps/shinkai-desktop/src-tauri/src/main.rs, apps/shinkai-desktop/src/components/playground-tool/hooks/use-tool-flow.ts, apps/shinkai-desktop/src/lib/notifications.ts, libs/shinkai-i18n/locales/en-US.json, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-i18n/locales/id-ID.json, libs/shinkai-i18n/locales/ja-JP.json, libs/shinkai-i18n/locales/tr-TR.json, libs/shinkai-i18n/locales/zh-CN.json, libs/shinkai-i18n/src/lib/default/index.ts
=> feat: code generation notification

apps/shinkai-desktop/src/components/chat/set-conversation-context.tsx, apps/shinkai-desktop/src/components/playground-tool/hooks/use-tool-flow.ts
- Updated the conversation context title to include a suffix for clarity.
- Changed the `propagateSelectionDown` property to true for improved selection behavior.
- Refactored the handling of tool result files to use `useMemo` for better performance and readability, this should improve the console tab showing of logs in the playground.
=> Refactor tool result handling and update conversation context display

apps/shinkai-desktop/src/components/chat/conversation-header.tsx, libs/shinkai-i18n/locales/en-US.json, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-i18n/locales/id-ID.json, libs/shinkai-i18n/locales/ja-JP.json, libs/shinkai-i18n/locales/tr-TR.json, libs/shinkai-i18n/locales/zh-CN.json, libs/shinkai-i18n/src/lib/default/index.ts
=> feat: add agent details

apps/shinkai-desktop/src/components/chat/chat-action-bar/ai-update-selection-action-bar.tsx, apps/shinkai-desktop/src/components/chat/components/message.tsx, apps/shinkai-desktop/src/components/playground-tool/components/ai-update-selection-tool.tsx, apps/shinkai-desktop/src/components/playground-tool/components/playground-chat.tsx, apps/shinkai-desktop/src/components/playground-tool/components/tool-playground.tsx, apps/shinkai-desktop/src/components/playground-tool/hooks/use-tool-flow.ts, apps/shinkai-desktop/src/components/tools/constants.ts, apps/shinkai-desktop/src/pages/tools-homepage.tsx, libs/shinkai-ui/src/components/chat/files-preview.tsx
- feat: improve tool results UI in conversation 
- feat: improve tool ai model selector
=> feat: ui improvements

apps/shinkai-desktop/src/components/error-boundary.tsx, apps/shinkai-desktop/src/pages/layout/main-layout.tsx, libs/shinkai-i18n/locales/en-US.json, libs/shinkai-i18n/locales/es-ES.json, libs/shinkai-i18n/locales/id-ID.json, libs/shinkai-i18n/locales/ja-JP.json, libs/shinkai-i18n/locales/tr-TR.json, libs/shinkai-i18n/locales/zh-CN.json, libs/shinkai-i18n/src/lib/default/index.ts, libs/shinkai-ui/src/assets/icons/general.tsx, libs/shinkai-ui/src/components/button.tsx
=> feat: group up secondary menu options

.github/workflows/pr-ci-healchecks.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, README.md, apps/shinkai-desktop/src-tauri/Cargo.lock, apps/shinkai-desktop/src-tauri/src/local_shinkai_node/process_handlers/shinkai_node_process_handler.rs, package-lock.json, package.json
Now, when the node health_check fails in the initialization process, we retry with a bigger timeout
=> fix: node initialization timeout

apps/shinkai-desktop/src/pages/layout/settings-layout.tsx, apps/shinkai-desktop/src/pages/shortcuts.tsx, apps/shinkai-desktop/src/routes/index.tsx, libs/shinkai-ui/src/assets/icons/general.tsx
=> feat: add keyboard shortcuts page
